### ISSUE TITLE
feat request: handling multiple languages

### ISSUE THREAD

**Issue by vanilla-extracts** [vanilla-extracts/website#2]
Adding an implementation for multiple languages:
- An optional `language.toml` in which additional languages can be configured:
```toml
[language]
default_language = "en"
supported_languages = ["en","fr"]

[en]
format = "{file_name}.md"

[fr]
format = "{file_name}.fr.md"
```

- serve the default language to root
- serve the supported languages to `www.example.com/{language_key}`
